version: '3'

services:
  db:
    image: postgres:14
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./pg_volume:/var/lib/postgresql/data
