name: App image build

on:
  push:
    branches:
      - "master"

jobs:
  server:
    runs-on: "ubuntu-latest"
    env:
      NODE_ENV: test
      WORKING_DIR: ./interfaces/graphile

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: feeled/flgsvo

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"