name: Cypress Tests CI

on:
  pull_request:
    branches:
      - "master"

jobs:
  e2e:
    runs-on: "ubuntu-latest"
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      WORKING_DIR: ./app

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Install TypeScript dependencies
        working-directory: ${{env.WORKING_DIR}}
        run: yarn

      - name: Build project
        working-directory: ${{env.WORKING_DIR}}
        run: yarn build

      - name: Start project in background
        working-directory: ${{env.WORKING_DIR}}
        run: yarn start &


      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ${{env.WORKING_DIR}}